server:
  port: 8031
spring:
  application:
    name: cloud-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: ms-movie,ms-movie-feign-hystrix-fallback-stream
  clusterNameExpression: "'default'"